### ISSUE TITLE
代码增强

### ISSUE THREAD

**Issue by specialpointcentral** [1604104se-hitwh/welcome#33]
针对 #32 
代码中有一部分，会将所有的Post从数据库中取出，可能会降低效率，看是否有其他解决办法

以上

**Comment by ruitard** [comment]
所有通知部分是要将所有通知都取出来，不过可以分页取（paginate）；
消息中心那建议只放最新的几条通知，取消未读通知，就跟学校的通知中心那样

**Comment by specialpointcentral** [comment]
还是分页取吧，之后通知多了加载会很慢，然后数据库会爆炸。
具体加载这东西刘好像用了。
https://bootstrap-table.com/
具体还要调整后台以及ajax。
可后期再处理
